# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/shrirang/Documents/openCV codes/cse408phase2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/shrirang/Documents/openCV codes/cse408phase2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/shrirang/Documents/openCV codes/cse408phase2/CMakeFiles" "/Users/shrirang/Documents/openCV codes/cse408phase2/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/shrirang/Documents/openCV codes/cse408phase2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named task1

# Build rule for target.
task1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task1
.PHONY : task1

# fast build rule for target.
task1/fast:
	$(MAKE) -f CMakeFiles/task1.dir/build.make CMakeFiles/task1.dir/build
.PHONY : task1/fast

#=============================================================================
# Target rules for targets named task2

# Build rule for target.
task2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task2
.PHONY : task2

# fast build rule for target.
task2/fast:
	$(MAKE) -f CMakeFiles/task2.dir/build.make CMakeFiles/task2.dir/build
.PHONY : task2/fast

#=============================================================================
# Target rules for targets named task3

# Build rule for target.
task3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task3
.PHONY : task3

# fast build rule for target.
task3/fast:
	$(MAKE) -f CMakeFiles/task3.dir/build.make CMakeFiles/task3.dir/build
.PHONY : task3/fast

#=============================================================================
# Target rules for targets named task4

# Build rule for target.
task4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task4
.PHONY : task4

# fast build rule for target.
task4/fast:
	$(MAKE) -f CMakeFiles/task4.dir/build.make CMakeFiles/task4.dir/build
.PHONY : task4/fast

#=============================================================================
# Target rules for targets named task4-shannon

# Build rule for target.
task4-shannon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task4-shannon
.PHONY : task4-shannon

# fast build rule for target.
task4-shannon/fast:
	$(MAKE) -f CMakeFiles/task4-shannon.dir/build.make CMakeFiles/task4-shannon.dir/build
.PHONY : task4-shannon/fast

#=============================================================================
# Target rules for targets named task4LZW

# Build rule for target.
task4LZW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task4LZW
.PHONY : task4LZW

# fast build rule for target.
task4LZW/fast:
	$(MAKE) -f CMakeFiles/task4LZW.dir/build.make CMakeFiles/task4LZW.dir/build
.PHONY : task4LZW/fast

#=============================================================================
# Target rules for targets named task4_ACD

# Build rule for target.
task4_ACD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task4_ACD
.PHONY : task4_ACD

# fast build rule for target.
task4_ACD/fast:
	$(MAKE) -f CMakeFiles/task4_ACD.dir/build.make CMakeFiles/task4_ACD.dir/build
.PHONY : task4_ACD/fast

#=============================================================================
# Target rules for targets named task4_NC

# Build rule for target.
task4_NC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task4_NC
.PHONY : task4_NC

# fast build rule for target.
task4_NC/fast:
	$(MAKE) -f CMakeFiles/task4_NC.dir/build.make CMakeFiles/task4_NC.dir/build
.PHONY : task4_NC/fast

#=============================================================================
# Target rules for targets named task5

# Build rule for target.
task5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task5
.PHONY : task5

# fast build rule for target.
task5/fast:
	$(MAKE) -f CMakeFiles/task5.dir/build.make CMakeFiles/task5.dir/build
.PHONY : task5/fast

#=============================================================================
# Target rules for targets named task5-1

# Build rule for target.
task5-1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task5-1
.PHONY : task5-1

# fast build rule for target.
task5-1/fast:
	$(MAKE) -f CMakeFiles/task5-1.dir/build.make CMakeFiles/task5-1.dir/build
.PHONY : task5-1/fast

#=============================================================================
# Target rules for targets named task5-2

# Build rule for target.
task5-2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 task5-2
.PHONY : task5-2

# fast build rule for target.
task5-2/fast:
	$(MAKE) -f CMakeFiles/task5-2.dir/build.make CMakeFiles/task5-2.dir/build
.PHONY : task5-2/fast

task1.o: task1.cpp.o

.PHONY : task1.o

# target to build an object file
task1.cpp.o:
	$(MAKE) -f CMakeFiles/task1.dir/build.make CMakeFiles/task1.dir/task1.cpp.o
.PHONY : task1.cpp.o

task1.i: task1.cpp.i

.PHONY : task1.i

# target to preprocess a source file
task1.cpp.i:
	$(MAKE) -f CMakeFiles/task1.dir/build.make CMakeFiles/task1.dir/task1.cpp.i
.PHONY : task1.cpp.i

task1.s: task1.cpp.s

.PHONY : task1.s

# target to generate assembly for a file
task1.cpp.s:
	$(MAKE) -f CMakeFiles/task1.dir/build.make CMakeFiles/task1.dir/task1.cpp.s
.PHONY : task1.cpp.s

task2.o: task2.cpp.o

.PHONY : task2.o

# target to build an object file
task2.cpp.o:
	$(MAKE) -f CMakeFiles/task2.dir/build.make CMakeFiles/task2.dir/task2.cpp.o
.PHONY : task2.cpp.o

task2.i: task2.cpp.i

.PHONY : task2.i

# target to preprocess a source file
task2.cpp.i:
	$(MAKE) -f CMakeFiles/task2.dir/build.make CMakeFiles/task2.dir/task2.cpp.i
.PHONY : task2.cpp.i

task2.s: task2.cpp.s

.PHONY : task2.s

# target to generate assembly for a file
task2.cpp.s:
	$(MAKE) -f CMakeFiles/task2.dir/build.make CMakeFiles/task2.dir/task2.cpp.s
.PHONY : task2.cpp.s

task3.o: task3.cpp.o

.PHONY : task3.o

# target to build an object file
task3.cpp.o:
	$(MAKE) -f CMakeFiles/task3.dir/build.make CMakeFiles/task3.dir/task3.cpp.o
.PHONY : task3.cpp.o

task3.i: task3.cpp.i

.PHONY : task3.i

# target to preprocess a source file
task3.cpp.i:
	$(MAKE) -f CMakeFiles/task3.dir/build.make CMakeFiles/task3.dir/task3.cpp.i
.PHONY : task3.cpp.i

task3.s: task3.cpp.s

.PHONY : task3.s

# target to generate assembly for a file
task3.cpp.s:
	$(MAKE) -f CMakeFiles/task3.dir/build.make CMakeFiles/task3.dir/task3.cpp.s
.PHONY : task3.cpp.s

task4-shannon.o: task4-shannon.cpp.o

.PHONY : task4-shannon.o

# target to build an object file
task4-shannon.cpp.o:
	$(MAKE) -f CMakeFiles/task4-shannon.dir/build.make CMakeFiles/task4-shannon.dir/task4-shannon.cpp.o
.PHONY : task4-shannon.cpp.o

task4-shannon.i: task4-shannon.cpp.i

.PHONY : task4-shannon.i

# target to preprocess a source file
task4-shannon.cpp.i:
	$(MAKE) -f CMakeFiles/task4-shannon.dir/build.make CMakeFiles/task4-shannon.dir/task4-shannon.cpp.i
.PHONY : task4-shannon.cpp.i

task4-shannon.s: task4-shannon.cpp.s

.PHONY : task4-shannon.s

# target to generate assembly for a file
task4-shannon.cpp.s:
	$(MAKE) -f CMakeFiles/task4-shannon.dir/build.make CMakeFiles/task4-shannon.dir/task4-shannon.cpp.s
.PHONY : task4-shannon.cpp.s

task4.o: task4.cpp.o

.PHONY : task4.o

# target to build an object file
task4.cpp.o:
	$(MAKE) -f CMakeFiles/task4.dir/build.make CMakeFiles/task4.dir/task4.cpp.o
.PHONY : task4.cpp.o

task4.i: task4.cpp.i

.PHONY : task4.i

# target to preprocess a source file
task4.cpp.i:
	$(MAKE) -f CMakeFiles/task4.dir/build.make CMakeFiles/task4.dir/task4.cpp.i
.PHONY : task4.cpp.i

task4.s: task4.cpp.s

.PHONY : task4.s

# target to generate assembly for a file
task4.cpp.s:
	$(MAKE) -f CMakeFiles/task4.dir/build.make CMakeFiles/task4.dir/task4.cpp.s
.PHONY : task4.cpp.s

task4LZW.o: task4LZW.cpp.o

.PHONY : task4LZW.o

# target to build an object file
task4LZW.cpp.o:
	$(MAKE) -f CMakeFiles/task4LZW.dir/build.make CMakeFiles/task4LZW.dir/task4LZW.cpp.o
.PHONY : task4LZW.cpp.o

task4LZW.i: task4LZW.cpp.i

.PHONY : task4LZW.i

# target to preprocess a source file
task4LZW.cpp.i:
	$(MAKE) -f CMakeFiles/task4LZW.dir/build.make CMakeFiles/task4LZW.dir/task4LZW.cpp.i
.PHONY : task4LZW.cpp.i

task4LZW.s: task4LZW.cpp.s

.PHONY : task4LZW.s

# target to generate assembly for a file
task4LZW.cpp.s:
	$(MAKE) -f CMakeFiles/task4LZW.dir/build.make CMakeFiles/task4LZW.dir/task4LZW.cpp.s
.PHONY : task4LZW.cpp.s

task4_ACD.o: task4_ACD.cpp.o

.PHONY : task4_ACD.o

# target to build an object file
task4_ACD.cpp.o:
	$(MAKE) -f CMakeFiles/task4_ACD.dir/build.make CMakeFiles/task4_ACD.dir/task4_ACD.cpp.o
.PHONY : task4_ACD.cpp.o

task4_ACD.i: task4_ACD.cpp.i

.PHONY : task4_ACD.i

# target to preprocess a source file
task4_ACD.cpp.i:
	$(MAKE) -f CMakeFiles/task4_ACD.dir/build.make CMakeFiles/task4_ACD.dir/task4_ACD.cpp.i
.PHONY : task4_ACD.cpp.i

task4_ACD.s: task4_ACD.cpp.s

.PHONY : task4_ACD.s

# target to generate assembly for a file
task4_ACD.cpp.s:
	$(MAKE) -f CMakeFiles/task4_ACD.dir/build.make CMakeFiles/task4_ACD.dir/task4_ACD.cpp.s
.PHONY : task4_ACD.cpp.s

task4_NC.o: task4_NC.cpp.o

.PHONY : task4_NC.o

# target to build an object file
task4_NC.cpp.o:
	$(MAKE) -f CMakeFiles/task4_NC.dir/build.make CMakeFiles/task4_NC.dir/task4_NC.cpp.o
.PHONY : task4_NC.cpp.o

task4_NC.i: task4_NC.cpp.i

.PHONY : task4_NC.i

# target to preprocess a source file
task4_NC.cpp.i:
	$(MAKE) -f CMakeFiles/task4_NC.dir/build.make CMakeFiles/task4_NC.dir/task4_NC.cpp.i
.PHONY : task4_NC.cpp.i

task4_NC.s: task4_NC.cpp.s

.PHONY : task4_NC.s

# target to generate assembly for a file
task4_NC.cpp.s:
	$(MAKE) -f CMakeFiles/task4_NC.dir/build.make CMakeFiles/task4_NC.dir/task4_NC.cpp.s
.PHONY : task4_NC.cpp.s

task5-1.o: task5-1.cpp.o

.PHONY : task5-1.o

# target to build an object file
task5-1.cpp.o:
	$(MAKE) -f CMakeFiles/task5-1.dir/build.make CMakeFiles/task5-1.dir/task5-1.cpp.o
.PHONY : task5-1.cpp.o

task5-1.i: task5-1.cpp.i

.PHONY : task5-1.i

# target to preprocess a source file
task5-1.cpp.i:
	$(MAKE) -f CMakeFiles/task5-1.dir/build.make CMakeFiles/task5-1.dir/task5-1.cpp.i
.PHONY : task5-1.cpp.i

task5-1.s: task5-1.cpp.s

.PHONY : task5-1.s

# target to generate assembly for a file
task5-1.cpp.s:
	$(MAKE) -f CMakeFiles/task5-1.dir/build.make CMakeFiles/task5-1.dir/task5-1.cpp.s
.PHONY : task5-1.cpp.s

task5-2.o: task5-2.cpp.o

.PHONY : task5-2.o

# target to build an object file
task5-2.cpp.o:
	$(MAKE) -f CMakeFiles/task5-2.dir/build.make CMakeFiles/task5-2.dir/task5-2.cpp.o
.PHONY : task5-2.cpp.o

task5-2.i: task5-2.cpp.i

.PHONY : task5-2.i

# target to preprocess a source file
task5-2.cpp.i:
	$(MAKE) -f CMakeFiles/task5-2.dir/build.make CMakeFiles/task5-2.dir/task5-2.cpp.i
.PHONY : task5-2.cpp.i

task5-2.s: task5-2.cpp.s

.PHONY : task5-2.s

# target to generate assembly for a file
task5-2.cpp.s:
	$(MAKE) -f CMakeFiles/task5-2.dir/build.make CMakeFiles/task5-2.dir/task5-2.cpp.s
.PHONY : task5-2.cpp.s

task5.o: task5.cpp.o

.PHONY : task5.o

# target to build an object file
task5.cpp.o:
	$(MAKE) -f CMakeFiles/task5.dir/build.make CMakeFiles/task5.dir/task5.cpp.o
.PHONY : task5.cpp.o

task5.i: task5.cpp.i

.PHONY : task5.i

# target to preprocess a source file
task5.cpp.i:
	$(MAKE) -f CMakeFiles/task5.dir/build.make CMakeFiles/task5.dir/task5.cpp.i
.PHONY : task5.cpp.i

task5.s: task5.cpp.s

.PHONY : task5.s

# target to generate assembly for a file
task5.cpp.s:
	$(MAKE) -f CMakeFiles/task5.dir/build.make CMakeFiles/task5.dir/task5.cpp.s
.PHONY : task5.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... task5-2"
	@echo "... task5-1"
	@echo "... task4_NC"
	@echo "... task5"
	@echo "... task4-shannon"
	@echo "... task2"
	@echo "... task4_ACD"
	@echo "... task3"
	@echo "... task1"
	@echo "... task4"
	@echo "... task4LZW"
	@echo "... task1.o"
	@echo "... task1.i"
	@echo "... task1.s"
	@echo "... task2.o"
	@echo "... task2.i"
	@echo "... task2.s"
	@echo "... task3.o"
	@echo "... task3.i"
	@echo "... task3.s"
	@echo "... task4-shannon.o"
	@echo "... task4-shannon.i"
	@echo "... task4-shannon.s"
	@echo "... task4.o"
	@echo "... task4.i"
	@echo "... task4.s"
	@echo "... task4LZW.o"
	@echo "... task4LZW.i"
	@echo "... task4LZW.s"
	@echo "... task4_ACD.o"
	@echo "... task4_ACD.i"
	@echo "... task4_ACD.s"
	@echo "... task4_NC.o"
	@echo "... task4_NC.i"
	@echo "... task4_NC.s"
	@echo "... task5-1.o"
	@echo "... task5-1.i"
	@echo "... task5-1.s"
	@echo "... task5-2.o"
	@echo "... task5-2.i"
	@echo "... task5-2.s"
	@echo "... task5.o"
	@echo "... task5.i"
	@echo "... task5.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

